// Copyright 2021 The Kubeflow Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/kubeflow/training-operator/pkg/apis/pytorch/v1/generated.proto

package v1

import (
	fmt "fmt"

	io "io"

	proto "github.com/gogo/protobuf/proto"
	github_com_gogo_protobuf_sortkeys "github.com/gogo/protobuf/sortkeys"
	github_com_kubeflow_common_pkg_apis_common_v1 "github.com/kubeflow/common/pkg/apis/common/v1"
	v11 "github.com/kubeflow/common/pkg/apis/common/v1"
	v2beta2 "k8s.io/api/autoscaling/v2beta2"

	math "math"
	math_bits "math/bits"
	reflect "reflect"

	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

func (m *ElasticPolicy) Reset()      { *m = ElasticPolicy{} }
func (*ElasticPolicy) ProtoMessage() {}
func (*ElasticPolicy) Descriptor() ([]byte, []int) {
	return fileDescriptor_e24f62ed66e0facd, []int{0}
}
func (m *ElasticPolicy) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ElasticPolicy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *ElasticPolicy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ElasticPolicy.Merge(m, src)
}
func (m *ElasticPolicy) XXX_Size() int {
	return m.Size()
}
func (m *ElasticPolicy) XXX_DiscardUnknown() {
	xxx_messageInfo_ElasticPolicy.DiscardUnknown(m)
}

var xxx_messageInfo_ElasticPolicy proto.InternalMessageInfo

func (m *PyTorchJob) Reset()      { *m = PyTorchJob{} }
func (*PyTorchJob) ProtoMessage() {}
func (*PyTorchJob) Descriptor() ([]byte, []int) {
	return fileDescriptor_e24f62ed66e0facd, []int{1}
}
func (m *PyTorchJob) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PyTorchJob) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *PyTorchJob) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PyTorchJob.Merge(m, src)
}
func (m *PyTorchJob) XXX_Size() int {
	return m.Size()
}
func (m *PyTorchJob) XXX_DiscardUnknown() {
	xxx_messageInfo_PyTorchJob.DiscardUnknown(m)
}

var xxx_messageInfo_PyTorchJob proto.InternalMessageInfo

func (m *PyTorchJobList) Reset()      { *m = PyTorchJobList{} }
func (*PyTorchJobList) ProtoMessage() {}
func (*PyTorchJobList) Descriptor() ([]byte, []int) {
	return fileDescriptor_e24f62ed66e0facd, []int{2}
}
func (m *PyTorchJobList) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PyTorchJobList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *PyTorchJobList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PyTorchJobList.Merge(m, src)
}
func (m *PyTorchJobList) XXX_Size() int {
	return m.Size()
}
func (m *PyTorchJobList) XXX_DiscardUnknown() {
	xxx_messageInfo_PyTorchJobList.DiscardUnknown(m)
}

var xxx_messageInfo_PyTorchJobList proto.InternalMessageInfo

func (m *PyTorchJobSpec) Reset()      { *m = PyTorchJobSpec{} }
func (*PyTorchJobSpec) ProtoMessage() {}
func (*PyTorchJobSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_e24f62ed66e0facd, []int{3}
}
func (m *PyTorchJobSpec) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PyTorchJobSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *PyTorchJobSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PyTorchJobSpec.Merge(m, src)
}
func (m *PyTorchJobSpec) XXX_Size() int {
	return m.Size()
}
func (m *PyTorchJobSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_PyTorchJobSpec.DiscardUnknown(m)
}

var xxx_messageInfo_PyTorchJobSpec proto.InternalMessageInfo

func (m *RDZVConf) Reset()      { *m = RDZVConf{} }
func (*RDZVConf) ProtoMessage() {}
func (*RDZVConf) Descriptor() ([]byte, []int) {
	return fileDescriptor_e24f62ed66e0facd, []int{4}
}
func (m *RDZVConf) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RDZVConf) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *RDZVConf) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RDZVConf.Merge(m, src)
}
func (m *RDZVConf) XXX_Size() int {
	return m.Size()
}
func (m *RDZVConf) XXX_DiscardUnknown() {
	xxx_messageInfo_RDZVConf.DiscardUnknown(m)
}

var xxx_messageInfo_RDZVConf proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ElasticPolicy)(nil), "github.com.kubeflow.training_operator.pkg.apis.pytorch.v1.ElasticPolicy")
	proto.RegisterType((*PyTorchJob)(nil), "github.com.kubeflow.training_operator.pkg.apis.pytorch.v1.PyTorchJob")
	proto.RegisterType((*PyTorchJobList)(nil), "github.com.kubeflow.training_operator.pkg.apis.pytorch.v1.PyTorchJobList")
	proto.RegisterType((*PyTorchJobSpec)(nil), "github.com.kubeflow.training_operator.pkg.apis.pytorch.v1.PyTorchJobSpec")
	proto.RegisterMapType((map[github_com_kubeflow_common_pkg_apis_common_v1.ReplicaType]v11.ReplicaSpec)(nil), "github.com.kubeflow.training_operator.pkg.apis.pytorch.v1.PyTorchJobSpec.PytorchReplicaSpecsEntry")
	proto.RegisterType((*RDZVConf)(nil), "github.com.kubeflow.training_operator.pkg.apis.pytorch.v1.RDZVConf")
}

func init() {
	proto.RegisterFile("github.com/kubeflow/training-operator/pkg/apis/pytorch/v1/generated.proto", fileDescriptor_e24f62ed66e0facd)
}

var fileDescriptor_e24f62ed66e0facd = []byte{
	// 944 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0x4d, 0x6f, 0x1b, 0x45,
	0x18, 0xce, 0x26, 0xb1, 0x63, 0x8f, 0x93, 0x34, 0x9d, 0x5e, 0x56, 0x91, 0x58, 0x47, 0xe6, 0x62,
	0x21, 0x65, 0x16, 0x5b, 0x15, 0x4a, 0x2a, 0x21, 0xa1, 0x6d, 0x23, 0xd5, 0x40, 0x82, 0x35, 0x2d,
	0x15, 0xaa, 0x90, 0xe8, 0x78, 0x3d, 0xd9, 0x6c, 0xbd, 0xbb, 0xb3, 0xec, 0x8c, 0x0d, 0xe6, 0x04,
	0xfd, 0x05, 0x88, 0xff, 0xc3, 0x3d, 0xc7, 0x1e, 0x2b, 0x0e, 0x86, 0x2c, 0x77, 0x6e, 0x5c, 0x38,
	0xa1, 0x99, 0x9d, 0xfd, 0x70, 0x9d, 0x4a, 0x84, 0xf6, 0xe6, 0x79, 0xf7, 0xf9, 0x78, 0xe7, 0x99,
	0x77, 0xc6, 0x60, 0xe0, 0xf9, 0xe2, 0x62, 0x3a, 0x42, 0x2e, 0x0b, 0xed, 0xc9, 0x74, 0x44, 0xcf,
	0x03, 0xf6, 0x9d, 0x2d, 0x12, 0xe2, 0x47, 0x7e, 0xe4, 0x1d, 0xb2, 0x98, 0x26, 0x44, 0xb0, 0xc4,
	0x8e, 0x27, 0x9e, 0x4d, 0x62, 0x9f, 0xdb, 0xf1, 0x5c, 0xb0, 0xc4, 0xbd, 0xb0, 0x67, 0x3d, 0xdb,
	0xa3, 0x91, 0xfc, 0x4a, 0xc7, 0x28, 0x4e, 0x98, 0x60, 0xf0, 0xb8, 0x94, 0x42, 0xb9, 0x14, 0xca,
	0xa5, 0xbe, 0xc9, 0xa5, 0x50, 0x3c, 0xf1, 0x90, 0x94, 0x42, 0x5a, 0x0a, 0xcd, 0x7a, 0xfb, 0x87,
	0x95, 0x2e, 0x3c, 0xe6, 0x31, 0x5b, 0x29, 0x8e, 0xa6, 0xe7, 0x6a, 0xa5, 0x16, 0xea, 0x57, 0xe6,
	0xb4, 0xff, 0xf1, 0x75, 0x4d, 0xbb, 0x2c, 0x0c, 0x59, 0x54, 0x76, 0xaa, 0xd7, 0xab, 0x8d, 0xee,
	0xa3, 0xc9, 0x11, 0x47, 0x3e, 0x93, 0x30, 0x9b, 0x4c, 0x05, 0xe3, 0x2e, 0x09, 0xfc, 0xc8, 0xb3,
	0x67, 0xfd, 0x11, 0x15, 0xa4, 0xbf, 0x82, 0xbf, 0x5b, 0xe2, 0x43, 0xe2, 0x5e, 0xf8, 0x11, 0x4d,
	0xe6, 0xa5, 0x4f, 0x48, 0x05, 0xb9, 0xce, 0xe5, 0xa3, 0x37, 0xb1, 0x92, 0x69, 0x24, 0xfc, 0x90,
	0xda, 0xdc, 0xbd, 0xa0, 0x21, 0x59, 0xe1, 0x1d, 0x73, 0xdf, 0xe3, 0x79, 0x8b, 0x2e, 0x8b, 0x44,
	0xc2, 0x82, 0x80, 0x26, 0x87, 0x39, 0x4d, 0x4a, 0x28, 0x2a, 0x7d, 0x9d, 0xda, 0xf9, 0xa5, 0x06,
	0x76, 0x4e, 0x02, 0xc2, 0x85, 0xef, 0x0e, 0x59, 0xe0, 0xbb, 0x73, 0xd8, 0x03, 0xad, 0xd0, 0x8f,
	0x30, 0x8d, 0x03, 0xdf, 0x25, 0xdc, 0x34, 0x0e, 0x8c, 0x6e, 0xcd, 0xb9, 0x95, 0x2e, 0xda, 0xad,
	0xd3, 0xb2, 0x8c, 0xab, 0x18, 0x45, 0x21, 0xdf, 0x17, 0x94, 0xf5, 0x0a, 0xa5, 0x2c, 0xe3, 0x2a,
	0x06, 0x7e, 0x02, 0x5a, 0xc9, 0xf8, 0x87, 0x99, 0x43, 0xdc, 0x09, 0x8d, 0xc6, 0xe6, 0xc6, 0x81,
	0xd1, 0x6d, 0x3a, 0x96, 0xa4, 0xe0, 0x07, 0x4f, 0x9f, 0xe8, 0xf2, 0x3f, 0xcb, 0x4b, 0x5c, 0xa5,
	0xc0, 0x2e, 0x68, 0xc8, 0xe5, 0x90, 0x25, 0xc2, 0xdc, 0x54, 0x8e, 0xdb, 0xe9, 0xa2, 0xdd, 0x90,
	0x78, 0x59, 0xc3, 0xc5, 0xd7, 0x1c, 0xf9, 0x90, 0x71, 0x61, 0xd6, 0x94, 0x51, 0x81, 0x94, 0x35,
	0x5c, 0x7c, 0x85, 0x1d, 0x50, 0x97, 0xbf, 0x07, 0x63, 0xb3, 0xae, 0x70, 0x20, 0x5d, 0xb4, 0xeb,
	0x12, 0x37, 0x78, 0x80, 0xf5, 0x17, 0xf8, 0x6d, 0xa6, 0x76, 0x9f, 0x45, 0xe7, 0xe6, 0xd6, 0xc1,
	0x46, 0xb7, 0xd5, 0xbf, 0x8f, 0xfe, 0xf7, 0x18, 0x23, 0x29, 0x2e, 0xa5, 0x9c, 0xbd, 0xcb, 0x45,
	0x7b, 0x2d, 0x6f, 0x4b, 0x56, 0x70, 0x61, 0x03, 0x11, 0x00, 0x5c, 0x90, 0x68, 0x4c, 0x02, 0x16,
	0x51, 0xb3, 0x71, 0x60, 0x74, 0x1b, 0xce, 0x6e, 0xba, 0x68, 0x83, 0x47, 0x45, 0x15, 0x57, 0x10,
	0xf0, 0x2e, 0xd8, 0x8e, 0x86, 0x09, 0x73, 0x87, 0x34, 0x39, 0x63, 0x63, 0x6a, 0x36, 0x55, 0x3c,
	0x7b, 0xe9, 0xa2, 0xbd, 0x7d, 0x56, 0xa9, 0xe3, 0x25, 0x54, 0x71, 0x8a, 0x5c, 0x90, 0x44, 0x70,
	0x13, 0xbc, 0x76, 0x8a, 0x59, 0x19, 0x57, 0x31, 0xf0, 0x4b, 0xb0, 0x15, 0x52, 0x91, 0xf8, 0x2e,
	0x37, 0x5b, 0x2a, 0x8a, 0x0f, 0xf4, 0x14, 0xca, 0x7d, 0xa2, 0xca, 0x45, 0x41, 0xfa, 0xa2, 0xa0,
	0x53, 0x05, 0x7f, 0x14, 0x53, 0xd7, 0xb9, 0xa5, 0x77, 0xbc, 0x95, 0xd5, 0x38, 0xce, 0xb5, 0x3a,
	0xbf, 0xae, 0x03, 0x30, 0x9c, 0x3f, 0x96, 0x19, 0x7d, 0xca, 0x46, 0xf0, 0x19, 0x68, 0xc8, 0x1b,
	0x33, 0x26, 0x82, 0xa8, 0x71, 0x6c, 0xf5, 0x3f, 0xac, 0xd8, 0x14, 0x37, 0xa5, 0xcc, 0x57, 0xa2,
	0x65, 0xb8, 0x5f, 0x8c, 0x9e, 0x53, 0x57, 0x9c, 0x52, 0x41, 0x1c, 0xa8, 0xcd, 0x40, 0x59, 0xc3,
	0x85, 0x2a, 0x9c, 0x80, 0x4d, 0x1e, 0x53, 0x57, 0x4d, 0x6e, 0xab, 0x3f, 0x78, 0x8b, 0xf3, 0x2c,
	0xdb, 0x56, 0x7b, 0xdc, 0xd6, 0xb6, 0x9b, 0x72, 0x85, 0x95, 0x09, 0x7c, 0x06, 0xea, 0x5c, 0x10,
	0x31, 0xe5, 0x6a, 0xea, 0x5b, 0xfd, 0xa3, 0x6b, 0xed, 0xb2, 0xb7, 0xa8, 0xf4, 0xd0, 0xeb, 0x59,
	0x0f, 0x49, 0x6d, 0xc5, 0x77, 0x76, 0xb5, 0x7a, 0x3d, 0x5b, 0x63, 0xad, 0xdb, 0xf9, 0xcd, 0x00,
	0xbb, 0x65, 0x23, 0x9f, 0xfb, 0x5c, 0xc0, 0xaf, 0x57, 0x32, 0x44, 0xff, 0x2d, 0x43, 0xc9, 0x56,
	0x09, 0x16, 0x03, 0x9a, 0x57, 0x2a, 0xf9, 0x3d, 0x07, 0x35, 0x5f, 0xd0, 0x50, 0x5e, 0x7d, 0x39,
	0x05, 0x27, 0xef, 0x24, 0x40, 0x67, 0x47, 0x3b, 0xd6, 0x06, 0x52, 0x1b, 0x67, 0x16, 0x9d, 0xbf,
	0x37, 0xab, 0x9b, 0x93, 0xb9, 0x42, 0x1f, 0x34, 0x93, 0x69, 0x94, 0xbd, 0x5f, 0x7a, 0x77, 0x37,
	0x0d, 0x15, 0xe7, 0x7c, 0xe7, 0xb6, 0x76, 0x6d, 0x16, 0x25, 0x5c, 0xaa, 0xc3, 0x9f, 0x0c, 0xb0,
	0x43, 0xab, 0xef, 0xa5, 0x9e, 0x99, 0x87, 0x6f, 0xb1, 0xe5, 0xa5, 0xf7, 0xd7, 0xb9, 0x9d, 0x2e,
	0xda, 0xcb, 0x4f, 0x32, 0x5e, 0x76, 0x84, 0x7f, 0x19, 0xe0, 0x8e, 0xa6, 0xeb, 0xf7, 0x54, 0xa6,
	0x20, 0xc7, 0x49, 0x86, 0x3f, 0x7a, 0x67, 0xd3, 0x8b, 0x86, 0xab, 0x26, 0x27, 0x91, 0x48, 0xe6,
	0xce, 0x57, 0x3a, 0xa3, 0x3b, 0x9a, 0x50, 0x45, 0xbc, 0xf8, 0xbd, 0x7d, 0x7c, 0xa3, 0x3f, 0x5b,
	0xa4, 0xd9, 0x8f, 0xe7, 0x31, 0xc5, 0xd7, 0x6d, 0x6c, 0xff, 0x85, 0x01, 0xcc, 0x37, 0xf5, 0x02,
	0xf7, 0xc0, 0xc6, 0x84, 0x66, 0xc7, 0xde, 0xc4, 0xf2, 0x27, 0x1c, 0x82, 0xda, 0x8c, 0x04, 0x53,
	0xaa, 0x8f, 0xe6, 0xde, 0x4d, 0x47, 0xa1, 0xb4, 0xc0, 0x99, 0xd0, 0xbd, 0xf5, 0x23, 0xa3, 0x73,
	0x06, 0x8a, 0xa7, 0x19, 0xbe, 0x57, 0xf1, 0x74, 0x5a, 0x3a, 0x8c, 0x8d, 0xcf, 0xe8, 0x3c, 0x6b,
	0xe0, 0xfd, 0x6a, 0x03, 0xcd, 0x72, 0x8e, 0x9f, 0xc8, 0xa2, 0xd6, 0x74, 0xba, 0x97, 0x57, 0xd6,
	0xda, 0xcb, 0x2b, 0x6b, 0xed, 0xd5, 0x95, 0xb5, 0xf6, 0x63, 0x6a, 0x19, 0x97, 0xa9, 0x65, 0xbc,
	0x4c, 0x2d, 0xe3, 0x55, 0x6a, 0x19, 0x7f, 0xa4, 0x96, 0xf1, 0xf3, 0x9f, 0xd6, 0xda, 0xd3, 0xf5,
	0x59, 0xef, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x6b, 0x54, 0xac, 0xea, 0x71, 0x09, 0x00, 0x00,
}

func (m *ElasticPolicy) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ElasticPolicy) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ElasticPolicy) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Metrics) > 0 {
		for iNdEx := len(m.Metrics) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Metrics[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenerated(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x5a
		}
	}
	if m.MaxRestarts != nil {
		i = encodeVarintGenerated(dAtA, i, uint64(*m.MaxRestarts))
		i--
		dAtA[i] = 0x50
	}
	if m.NProcPerNode != nil {
		i = encodeVarintGenerated(dAtA, i, uint64(*m.NProcPerNode))
		i--
		dAtA[i] = 0x48
	}
	if m.Standalone != nil {
		i--
		if *m.Standalone {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x40
	}
	if len(m.RDZVConf) > 0 {
		for iNdEx := len(m.RDZVConf) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.RDZVConf[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenerated(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x3a
		}
	}
	if m.RDZVID != nil {
		i -= len(*m.RDZVID)
		copy(dAtA[i:], *m.RDZVID)
		i = encodeVarintGenerated(dAtA, i, uint64(len(*m.RDZVID)))
		i--
		dAtA[i] = 0x32
	}
	if m.RDZVHost != nil {
		i -= len(*m.RDZVHost)
		copy(dAtA[i:], *m.RDZVHost)
		i = encodeVarintGenerated(dAtA, i, uint64(len(*m.RDZVHost)))
		i--
		dAtA[i] = 0x2a
	}
	if m.RDZVPort != nil {
		i = encodeVarintGenerated(dAtA, i, uint64(*m.RDZVPort))
		i--
		dAtA[i] = 0x20
	}
	if m.RDZVBackend != nil {
		i -= len(*m.RDZVBackend)
		copy(dAtA[i:], *m.RDZVBackend)
		i = encodeVarintGenerated(dAtA, i, uint64(len(*m.RDZVBackend)))
		i--
		dAtA[i] = 0x1a
	}
	if m.MaxReplicas != nil {
		i = encodeVarintGenerated(dAtA, i, uint64(*m.MaxReplicas))
		i--
		dAtA[i] = 0x10
	}
	if m.MinReplicas != nil {
		i = encodeVarintGenerated(dAtA, i, uint64(*m.MinReplicas))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *PyTorchJob) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PyTorchJob) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PyTorchJob) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Status.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size, err := m.Spec.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size, err := m.ObjectMeta.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *PyTorchJobList) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PyTorchJobList) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PyTorchJobList) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Items) > 0 {
		for iNdEx := len(m.Items) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Items[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenerated(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.ListMeta.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *PyTorchJobSpec) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PyTorchJobSpec) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PyTorchJobSpec) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.PyTorchReplicaSpecs) > 0 {
		keysForPyTorchReplicaSpecs := make([]string, 0, len(m.PyTorchReplicaSpecs))
		for k := range m.PyTorchReplicaSpecs {
			keysForPyTorchReplicaSpecs = append(keysForPyTorchReplicaSpecs, string(k))
		}
		github_com_gogo_protobuf_sortkeys.Strings(keysForPyTorchReplicaSpecs)
		for iNdEx := len(keysForPyTorchReplicaSpecs) - 1; iNdEx >= 0; iNdEx-- {
			v := m.PyTorchReplicaSpecs[github_com_kubeflow_common_pkg_apis_common_v1.ReplicaType(keysForPyTorchReplicaSpecs[iNdEx])]
			baseI := i
			{
				size, err := (v).MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenerated(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
			i -= len(keysForPyTorchReplicaSpecs[iNdEx])
			copy(dAtA[i:], keysForPyTorchReplicaSpecs[iNdEx])
			i = encodeVarintGenerated(dAtA, i, uint64(len(keysForPyTorchReplicaSpecs[iNdEx])))
			i--
			dAtA[i] = 0xa
			i = encodeVarintGenerated(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0x1a
		}
	}
	if m.ElasticPolicy != nil {
		{
			size, err := m.ElasticPolicy.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenerated(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	{
		size, err := m.RunPolicy.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *RDZVConf) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RDZVConf) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RDZVConf) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	i -= len(m.Value)
	copy(dAtA[i:], m.Value)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.Value)))
	i--
	dAtA[i] = 0x12
	i -= len(m.Key)
	copy(dAtA[i:], m.Key)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.Key)))
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGenerated(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenerated(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ElasticPolicy) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.MinReplicas != nil {
		n += 1 + sovGenerated(uint64(*m.MinReplicas))
	}
	if m.MaxReplicas != nil {
		n += 1 + sovGenerated(uint64(*m.MaxReplicas))
	}
	if m.RDZVBackend != nil {
		l = len(*m.RDZVBackend)
		n += 1 + l + sovGenerated(uint64(l))
	}
	if m.RDZVPort != nil {
		n += 1 + sovGenerated(uint64(*m.RDZVPort))
	}
	if m.RDZVHost != nil {
		l = len(*m.RDZVHost)
		n += 1 + l + sovGenerated(uint64(l))
	}
	if m.RDZVID != nil {
		l = len(*m.RDZVID)
		n += 1 + l + sovGenerated(uint64(l))
	}
	if len(m.RDZVConf) > 0 {
		for _, e := range m.RDZVConf {
			l = e.Size()
			n += 1 + l + sovGenerated(uint64(l))
		}
	}
	if m.Standalone != nil {
		n += 2
	}
	if m.NProcPerNode != nil {
		n += 1 + sovGenerated(uint64(*m.NProcPerNode))
	}
	if m.MaxRestarts != nil {
		n += 1 + sovGenerated(uint64(*m.MaxRestarts))
	}
	if len(m.Metrics) > 0 {
		for _, e := range m.Metrics {
			l = e.Size()
			n += 1 + l + sovGenerated(uint64(l))
		}
	}
	return n
}

func (m *PyTorchJob) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ObjectMeta.Size()
	n += 1 + l + sovGenerated(uint64(l))
	l = m.Spec.Size()
	n += 1 + l + sovGenerated(uint64(l))
	l = m.Status.Size()
	n += 1 + l + sovGenerated(uint64(l))
	return n
}

func (m *PyTorchJobList) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ListMeta.Size()
	n += 1 + l + sovGenerated(uint64(l))
	if len(m.Items) > 0 {
		for _, e := range m.Items {
			l = e.Size()
			n += 1 + l + sovGenerated(uint64(l))
		}
	}
	return n
}

func (m *PyTorchJobSpec) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.RunPolicy.Size()
	n += 1 + l + sovGenerated(uint64(l))
	if m.ElasticPolicy != nil {
		l = m.ElasticPolicy.Size()
		n += 1 + l + sovGenerated(uint64(l))
	}
	if len(m.PyTorchReplicaSpecs) > 0 {
		for k, v := range m.PyTorchReplicaSpecs {
			_ = k
			_ = v
			l = v.Size()
			mapEntrySize := 1 + len(k) + sovGenerated(uint64(len(k))) + 1 + l + sovGenerated(uint64(l))
			n += mapEntrySize + 1 + sovGenerated(uint64(mapEntrySize))
		}
	}
	return n
}

func (m *RDZVConf) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Key)
	n += 1 + l + sovGenerated(uint64(l))
	l = len(m.Value)
	n += 1 + l + sovGenerated(uint64(l))
	return n
}

func sovGenerated(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenerated(x uint64) (n int) {
	return sovGenerated(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *ElasticPolicy) String() string {
	if this == nil {
		return "nil"
	}
	repeatedStringForRDZVConf := "[]RDZVConf{"
	for _, f := range this.RDZVConf {
		repeatedStringForRDZVConf += strings.Replace(strings.Replace(f.String(), "RDZVConf", "RDZVConf", 1), `&`, ``, 1) + ","
	}
	repeatedStringForRDZVConf += "}"
	repeatedStringForMetrics := "[]MetricSpec{"
	for _, f := range this.Metrics {
		repeatedStringForMetrics += fmt.Sprintf("%v", f) + ","
	}
	repeatedStringForMetrics += "}"
	s := strings.Join([]string{`&ElasticPolicy{`,
		`MinReplicas:` + valueToStringGenerated(this.MinReplicas) + `,`,
		`MaxReplicas:` + valueToStringGenerated(this.MaxReplicas) + `,`,
		`RDZVBackend:` + valueToStringGenerated(this.RDZVBackend) + `,`,
		`RDZVPort:` + valueToStringGenerated(this.RDZVPort) + `,`,
		`RDZVHost:` + valueToStringGenerated(this.RDZVHost) + `,`,
		`RDZVID:` + valueToStringGenerated(this.RDZVID) + `,`,
		`RDZVConf:` + repeatedStringForRDZVConf + `,`,
		`Standalone:` + valueToStringGenerated(this.Standalone) + `,`,
		`NProcPerNode:` + valueToStringGenerated(this.NProcPerNode) + `,`,
		`MaxRestarts:` + valueToStringGenerated(this.MaxRestarts) + `,`,
		`Metrics:` + repeatedStringForMetrics + `,`,
		`}`,
	}, "")
	return s
}
func (this *PyTorchJob) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&PyTorchJob{`,
		`ObjectMeta:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.ObjectMeta), "ObjectMeta", "v1.ObjectMeta", 1), `&`, ``, 1) + `,`,
		`Spec:` + strings.Replace(strings.Replace(this.Spec.String(), "PyTorchJobSpec", "PyTorchJobSpec", 1), `&`, ``, 1) + `,`,
		`Status:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.Status), "JobStatus", "v11.JobStatus", 1), `&`, ``, 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *PyTorchJobList) String() string {
	if this == nil {
		return "nil"
	}
	repeatedStringForItems := "[]PyTorchJob{"
	for _, f := range this.Items {
		repeatedStringForItems += strings.Replace(strings.Replace(f.String(), "PyTorchJob", "PyTorchJob", 1), `&`, ``, 1) + ","
	}
	repeatedStringForItems += "}"
	s := strings.Join([]string{`&PyTorchJobList{`,
		`ListMeta:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.ListMeta), "ListMeta", "v1.ListMeta", 1), `&`, ``, 1) + `,`,
		`Items:` + repeatedStringForItems + `,`,
		`}`,
	}, "")
	return s
}
func (this *PyTorchJobSpec) String() string {
	if this == nil {
		return "nil"
	}
	keysForPyTorchReplicaSpecs := make([]string, 0, len(this.PyTorchReplicaSpecs))
	for k := range this.PyTorchReplicaSpecs {
		keysForPyTorchReplicaSpecs = append(keysForPyTorchReplicaSpecs, string(k))
	}
	github_com_gogo_protobuf_sortkeys.Strings(keysForPyTorchReplicaSpecs)
	mapStringForPyTorchReplicaSpecs := "map[github_com_kubeflow_common_pkg_apis_common_v1.ReplicaType]v11.ReplicaSpec{"
	for _, k := range keysForPyTorchReplicaSpecs {
		mapStringForPyTorchReplicaSpecs += fmt.Sprintf("%v: %v,", k, this.PyTorchReplicaSpecs[github_com_kubeflow_common_pkg_apis_common_v1.ReplicaType(k)])
	}
	mapStringForPyTorchReplicaSpecs += "}"
	s := strings.Join([]string{`&PyTorchJobSpec{`,
		`RunPolicy:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.RunPolicy), "RunPolicy", "v11.RunPolicy", 1), `&`, ``, 1) + `,`,
		`ElasticPolicy:` + strings.Replace(this.ElasticPolicy.String(), "ElasticPolicy", "ElasticPolicy", 1) + `,`,
		`PyTorchReplicaSpecs:` + mapStringForPyTorchReplicaSpecs + `,`,
		`}`,
	}, "")
	return s
}
func (this *RDZVConf) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&RDZVConf{`,
		`Key:` + fmt.Sprintf("%v", this.Key) + `,`,
		`Value:` + fmt.Sprintf("%v", this.Value) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringGenerated(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *ElasticPolicy) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ElasticPolicy: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ElasticPolicy: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinReplicas", wireType)
			}
			var v int32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.MinReplicas = &v
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxReplicas", wireType)
			}
			var v int32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.MaxReplicas = &v
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RDZVBackend", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := RDZVBackend(dAtA[iNdEx:postIndex])
			m.RDZVBackend = &s
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RDZVPort", wireType)
			}
			var v int32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.RDZVPort = &v
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RDZVHost", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.RDZVHost = &s
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RDZVID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.RDZVID = &s
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RDZVConf", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RDZVConf = append(m.RDZVConf, RDZVConf{})
			if err := m.RDZVConf[len(m.RDZVConf)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Standalone", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			b := bool(v != 0)
			m.Standalone = &b
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NProcPerNode", wireType)
			}
			var v int32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.NProcPerNode = &v
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxRestarts", wireType)
			}
			var v int32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.MaxRestarts = &v
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Metrics", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Metrics = append(m.Metrics, v2beta2.MetricSpec{})
			if err := m.Metrics[len(m.Metrics)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PyTorchJob) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PyTorchJob: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PyTorchJob: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ObjectMeta", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ObjectMeta.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Spec", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Spec.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Status.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PyTorchJobList) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PyTorchJobList: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PyTorchJobList: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ListMeta", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ListMeta.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Items", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Items = append(m.Items, PyTorchJob{})
			if err := m.Items[len(m.Items)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PyTorchJobSpec) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PyTorchJobSpec: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PyTorchJobSpec: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RunPolicy", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.RunPolicy.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ElasticPolicy", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ElasticPolicy == nil {
				m.ElasticPolicy = &ElasticPolicy{}
			}
			if err := m.ElasticPolicy.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PyTorchReplicaSpecs", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.PyTorchReplicaSpecs == nil {
				m.PyTorchReplicaSpecs = make(map[github_com_kubeflow_common_pkg_apis_common_v1.ReplicaType]*v11.ReplicaSpec)
			}
			var mapkey github_com_kubeflow_common_pkg_apis_common_v1.ReplicaType
			mapvalue := &v11.ReplicaSpec{}
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowGenerated
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowGenerated
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthGenerated
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey < 0 {
						return ErrInvalidLengthGenerated
					}
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = github_com_kubeflow_common_pkg_apis_common_v1.ReplicaType(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var mapmsglen int
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowGenerated
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapmsglen |= int(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					if mapmsglen < 0 {
						return ErrInvalidLengthGenerated
					}
					postmsgIndex := iNdEx + mapmsglen
					if postmsgIndex < 0 {
						return ErrInvalidLengthGenerated
					}
					if postmsgIndex > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = &v11.ReplicaSpec{}
					if err := mapvalue.Unmarshal(dAtA[iNdEx:postmsgIndex]); err != nil {
						return err
					}
					iNdEx = postmsgIndex
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipGenerated(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if (skippy < 0) || (iNdEx+skippy) < 0 {
						return ErrInvalidLengthGenerated
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.PyTorchReplicaSpecs[github_com_kubeflow_common_pkg_apis_common_v1.ReplicaType(mapkey)] = mapvalue
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RDZVConf) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RDZVConf: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RDZVConf: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Key", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Key = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Value", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Value = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenerated(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenerated
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenerated
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenerated
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenerated        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenerated          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenerated = fmt.Errorf("proto: unexpected end of group")
)
